### PR TITLE
Update readme – more detailed deploy instructions

### PR DESCRIPTION
**Pull request by TSMMark**

### CODE REVIEW

**Comment by TSMMark** [comment]
@RedBankWeb PTAL

**Comment by RedBankWeb** [comment]
Van,
Thank you for the instructions, but I have some issues.
1) I can't get Heroku to install.  It comes up with a big red box that says for my protection it won't install.  Contact site admin.

2) the GitHub is different on Apple vs PCs.   For instance I don't have many of the menu options you and hte website tutorials are referencing.  (the simplest example is the edit pencil.

3) This has lead me to use ATOM for my editor.

It seems I have all the updated files in my current local repository, but I can't seem to push them to the remote repository to go live.

Any suggestions?

**Review by RedBankWeb — APPROVED** [review]
I read this, but so many of the menu items and codes don't appear on my version of GitHub Desktop

**Comment by TSMMark** [comment]
Are you sure you installed the right github desktop app? The screenshots look pretty identical to the mac one

https://www.google.com/search?q=github+desktop+windows&sxsrf=ALeKk01Fra32G2PF-Q2SNOWrtAWaIXtVQA:1584733374693&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiryvLu56noAhX8knIEHTvXBsYQ_AUoAnoECAwQBA&biw=1680&bih=948#imgrc=HgxdNRdT2j-PVM

image

**Comment by TSMMark** [comment]
Maybe you are conflating github.com website with the desktop application? They each have their own use and purpose

**Comment by TSMMark** [comment]
> I can't get Heroku to install. It comes up with a big red box that says for my protection it won't install.

Idk what that means but you should be able to install programs on your own computer. Maybe try installing a better shell since windows cmd.exe is trash. people seem to like Git bash https://gitforwindows.org/

^ Oh maybe that GUI is what you installed instead of Github Desktop? Install Github Desktop from here: https://desktop.github.com/

**Comment by TSMMark** [comment]
FTR "git" is not synonymous with "github"... You can think of "git" as a protocol, like HTTP or FTP, and github.com as a repository host. 

There are many other git repository hosts out there, such as bitbucket, GitLab, SourceForge, etc. The same way there are any number of FTP clients, like filezilla, cyberduck, dreamweaver, etc.

**Pull request merged**
